# Generated by Django 4.0.7 on 2022-09-17 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_agrege_tabla_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='figuras', to='gestion.categoria')),
            ],
            options={
                'db_table': 'figuras',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroVeces', models.IntegerField(db_column='num_veces')),
                ('tipo', models.CharField(choices=[['NORMAL', 'NORMAL'], ['ESPECIAL', 'ESPECIAL'], ['ESCUDO', 'ESCUDO']], max_length=25)),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='figura_registros', to='gestion.figura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registros',
            },
        ),
    ]
